# https://docs.docker.com/engine/logging/drivers/json-file/
- set_fact:
    _docker_daemon_options: "{{ _docker_daemon_options | default({}) | combine({'log-driver': docker_log_driver, 'log-opts': docker_log_opts | dict2items | rejectattr('value', 'none') | items2dict}) }}"