[tox]
envlist =
    offline-prepare
    offline-install
    offline-prepare-install
    default

[testenv]
deps =
    ansible-core==2.20.7 # https://github.com/ansible-community/molecule-plugins/issues/363
    molecule
    molecule-plugins[docker]

setenv =
    offline-prepare: MOLECULE_SCENARIO=offline-prepare
    offline-install: MOLECULE_SCENARIO=offline-install
    offline-install: TEST_NETWORK_MODE=none
    offline-prepare-install: MOLECULE_SCENARIO=offline-prepare-install
commands =
    molecule --base-config molecule/shared/base.yml test -s {env:MOLECULE_SCENARIO:default}
